# --------------------
# Define non-modifiable values
# --------------------


# ==================== Alas ====================

Alas:
  Emulator:
    ControlMethod: MaaTouch
  Optimization:
    ScreenshotInterval: 0.2
    CombatScreenshotInterval: 1.0
Restart:
  Scheduler:
    Enable:
      type: state
      value: true
      option: [ true, ]
      option_bold: [ true, ]
    ServerUpdate: 04:00

# ==================== Daily ====================
Freebies:
  Scheduler:
    Enable:
      type: checkbox
      value: true
      display: true

ZhaoCai:
  Scheduler:
    Enable:
      type: checkbox
      value: true
      display: true
Mission:
  Scheduler:
    Enable:
      type: checkbox
      value: true
      display: true

# ==================== Weekly ====================

