# --------------------
# Define argument group of tasks.
# --------------------

# ==================== Alas ====================

Alas:
  menu: 'list'
  page: 'setting'
  tasks:
    Alas:
      - Emulator
      - EmulatorInfo
      - Error
      - Optimization
    Restart:
      - Scheduler

# ==================== Daily ====================

Daily:
  menu: 'list'
  page: 'setting'
  tasks:
    Mission:
      - Scheduler
    Freebies:
      - Scheduler
      - Mail

# ==================== Weekly ====================




# ==================== Tool ====================

#Tool:
#  menu: 'list'
#  page: 'tool'
#  tasks:
#    Daemon:
#      - Daemon
#    PlannerScan:
#      - PlannerScan
