name: Webapp Release
on:
  push:
    branches:
      - main
    paths:
      - 'webapp/**'
  pull_request:
    paths:
      - 'webapp/**'
  workflow_dispatch:

concurrency:
  group: webapp-release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  webapp_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Call webapp release workflow
        uses: ./.github/workflows/webapp-release-delegate.yml
        with:
          dry-run: ${{ github.event_name != 'push' || github.ref_name != 'main' }}

  # 或者直接内联 webapp 的构建步骤
  webapp_build:
    strategy:
      fail-fast: true
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: webapp/package-lock.json

      - name: Install dependencies
        working-directory: webapp
        run: npm ci
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

      - name: Build webapp
        working-directory: webapp
        run: npm run build

      - name: Package and release
        working-directory: webapp
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 6
          retry_wait_seconds: 15
          retry_on: error
          shell: 'bash'
          command: npx --no-install electron-builder --config .electron-builder.config.js --publish ${{ github.event_name == 'push' && github.ref_name == 'main' && 'always' || 'never' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}