name: Webapp Release
on:
  push:
    branches:
      - main
    paths:
      - 'webapp/**'
  pull_request:
    paths:
      - 'webapp/**'
  workflow_dispatch:

concurrency:
  group: webapp-release-${{ github.ref }}
  cancel-in-progress: false

defaults:
  run:
    shell: 'bash'

jobs:
  webapp_build:
    strategy:
      fail-fast: true
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js with retry
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          retry_wait_seconds: 30
          command: echo "Preparing Node.js setup..."

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: webapp/package-lock.json

      - name: Install dependencies
        working-directory: webapp
        run: npm ci --legacy-peer-deps
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

      - name: Build webapp
        working-directory: webapp
        run: npm run build

      - name: Package and release
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 6
          retry_wait_seconds: 15
          retry_on: error
          shell: 'bash'
          command: |
            cd webapp  
            npx --no-install electron-builder --config .electron-builder.config.js --publish ${{ github.event_name == 'push' && github.ref_name == 'main' && 'always' || 'never' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}