name: Webapp Release
on:
  push:
    branches:
      - main
    paths:
      - 'webapp/**'
  pull_request:
    paths:
      - 'webapp/**'
  workflow_dispatch:

concurrency:
  group: webapp-release-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: 'bash'

jobs:
  webapp_build:
    strategy:
      fail-fast: true
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: webapp/package-lock.json

      - name: Install dependencies
        working-directory: webapp
        run: npm ci
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

      - name: Build webapp
        working-directory: webapp
        run: npm run build

      - name: Package and release
        working-directory: webapp
        run: npx --no-install electron-builder --config .electron-builder.config.js --publish ${{ github.event_name == 'push' && github.ref_name == 'main' && 'always' || 'never' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}